CREATE TABLE IF NOT EXISTS auth_refresh_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ NULL,
  last_used_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_sessions_user_id
  ON auth_refresh_sessions(user_id);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_sessions_active
  ON auth_refresh_sessions(token_hash, expires_at)
  WHERE revoked_at IS NULL;
