CREATE EXTENSION IF NOT EXISTS btree_gist;

DO $$
BEGIN
  CREATE TYPE academic_period_status AS ENUM ('planned', 'active', 'closed');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE academic_years (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(20) NOT NULL UNIQUE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status academic_period_status NOT NULL DEFAULT 'planned',
  is_locked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (start_date <= end_date),
  EXCLUDE USING gist (daterange(start_date, end_date, '[]') WITH &&)
);

CREATE TABLE semesters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year_id BIGINT NOT NULL REFERENCES academic_years(id) ON DELETE RESTRICT,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status academic_period_status NOT NULL DEFAULT 'planned',
  is_locked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (start_date <= end_date),
  UNIQUE (academic_year_id, code),
  EXCLUDE USING gist (
    academic_year_id WITH =,
    daterange(start_date, end_date, '[]') WITH &&
  )
);

CREATE UNIQUE INDEX uq_academic_years_single_active
  ON academic_years ((status))
  WHERE status = 'active';

CREATE UNIQUE INDEX uq_semesters_single_active
  ON semesters ((status))
  WHERE status = 'active';

CREATE INDEX idx_academic_years_status_dates
  ON academic_years(status, start_date DESC, end_date DESC);

CREATE INDEX idx_semesters_year_dates
  ON semesters(academic_year_id, start_date, end_date);

CREATE OR REPLACE FUNCTION validate_semester_academic_year()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  year_start DATE;
  year_end DATE;
BEGIN
  SELECT start_date, end_date
  INTO year_start, year_end
  FROM academic_years
  WHERE id = NEW.academic_year_id;

  IF year_start IS NULL THEN
    RAISE EXCEPTION 'Academic year does not exist';
  END IF;

  IF NEW.start_date < year_start OR NEW.end_date > year_end THEN
    RAISE EXCEPTION 'Semester dates must be inside the academic year';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_semester_academic_year
BEFORE INSERT OR UPDATE OF academic_year_id, start_date, end_date
ON semesters
FOR EACH ROW EXECUTE FUNCTION validate_semester_academic_year();

CREATE TRIGGER trg_academic_years_updated_at
BEFORE UPDATE ON academic_years
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_semesters_updated_at
BEFORE UPDATE ON semesters
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

WITH legacy_years AS (
  SELECT DISTINCT school_year AS name
  FROM (
    SELECT school_year FROM classrooms
    UNION
    SELECT school_year FROM timetables
  ) source
  WHERE school_year ~ '^[0-9]{4}-[0-9]{4}$'
),
valid_years AS (
  SELECT
    name,
    split_part(name, '-', 1)::INTEGER AS start_year,
    split_part(name, '-', 2)::INTEGER AS end_year
  FROM legacy_years
  WHERE split_part(name, '-', 2)::INTEGER =
    split_part(name, '-', 1)::INTEGER + 1
)
INSERT INTO academic_years (name, start_date, end_date, status)
SELECT
  name,
  make_date(start_year, 9, 1),
  make_date(end_year, 8, 31),
  CASE
    WHEN CURRENT_DATE BETWEEN make_date(start_year, 9, 1)
      AND make_date(end_year, 8, 31)
    THEN 'active'::academic_period_status
    ELSE 'planned'::academic_period_status
  END
FROM valid_years
ORDER BY start_year
ON CONFLICT (name) DO NOTHING;

INSERT INTO semesters (
  academic_year_id,
  name,
  code,
  start_date,
  end_date,
  status
)
SELECT
  ay.id,
  semester.name,
  semester.code,
  semester.start_date,
  semester.end_date,
  CASE
    WHEN ay.status = 'active'
      AND CURRENT_DATE BETWEEN semester.start_date AND semester.end_date
    THEN 'active'::academic_period_status
    ELSE 'planned'::academic_period_status
  END
FROM academic_years ay
CROSS JOIN LATERAL (
  VALUES
    (
      'Học kỳ 1',
      'HK1',
      ay.start_date,
      make_date(EXTRACT(YEAR FROM ay.end_date)::INTEGER, 1, 15)
    ),
    (
      'Học kỳ 2',
      'HK2',
      make_date(EXTRACT(YEAR FROM ay.end_date)::INTEGER, 1, 16),
      make_date(EXTRACT(YEAR FROM ay.end_date)::INTEGER, 5, 31)
    )
) AS semester(name, code, start_date, end_date)
ON CONFLICT (academic_year_id, code) DO NOTHING;

ALTER TABLE classrooms
  ADD COLUMN academic_year_id BIGINT REFERENCES academic_years(id) ON DELETE RESTRICT;

ALTER TABLE timetables
  ADD COLUMN academic_year_id BIGINT REFERENCES academic_years(id) ON DELETE RESTRICT,
  ADD COLUMN semester_id BIGINT REFERENCES semesters(id) ON DELETE RESTRICT;

UPDATE classrooms classroom
SET academic_year_id = academic_year.id
FROM academic_years academic_year
WHERE classroom.academic_year_id IS NULL
  AND academic_year.name = classroom.school_year;

UPDATE timetables timetable
SET academic_year_id = academic_year.id
FROM academic_years academic_year
WHERE timetable.academic_year_id IS NULL
  AND academic_year.name = timetable.school_year;

UPDATE timetables timetable
SET semester_id = semester.id
FROM semesters semester
WHERE timetable.semester_id IS NULL
  AND semester.academic_year_id = timetable.academic_year_id
  AND (
    (semester.code = 'HK1' AND (
      timetable.semester ~* '(^|[^0-9])1([^0-9]|$)'
      OR lower(timetable.semester) IN ('hk1', 'hki', 'hoc ky i', 'học kỳ i')
    ))
    OR
    (semester.code = 'HK2' AND (
      timetable.semester ~* '(^|[^0-9])2([^0-9]|$)'
      OR lower(timetable.semester) IN ('hk2', 'hkii', 'hoc ky ii', 'học kỳ ii')
    ))
  );

CREATE INDEX idx_classrooms_academic_year
  ON classrooms(academic_year_id);

CREATE INDEX idx_timetables_academic_period
  ON timetables(academic_year_id, semester_id);

CREATE UNIQUE INDEX uq_classrooms_name_academic_year
  ON classrooms(name, academic_year_id)
  WHERE academic_year_id IS NOT NULL;

