CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  subject_group VARCHAR(80) NOT NULL DEFAULT 'other',
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (code ~ '^[A-Z0-9_]{2,30}$')
);

CREATE TABLE curriculum_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year_id BIGINT NOT NULL
    REFERENCES academic_years(id) ON DELETE RESTRICT,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
  grade_level INTEGER NOT NULL CHECK (grade_level BETWEEN 10 AND 12),
  periods_per_week NUMERIC(4,1) NOT NULL CHECK (periods_per_week > 0),
  is_required BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (academic_year_id, subject_id, grade_level)
);

CREATE INDEX idx_subjects_active_group
  ON subjects(is_active, subject_group, name);

CREATE INDEX idx_curriculum_year_grade_active
  ON curriculum_subjects(academic_year_id, grade_level, is_active);

CREATE TRIGGER trg_subjects_updated_at
BEFORE UPDATE ON subjects
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_curriculum_subjects_updated_at
BEFORE UPDATE ON curriculum_subjects
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE timetable_items
  ADD COLUMN subject_id BIGINT REFERENCES subjects(id) ON DELETE RESTRICT;

CREATE INDEX idx_timetable_items_subject
  ON timetable_items(subject_id);

INSERT INTO subjects (code, name, subject_group)
VALUES
  ('TOAN', 'Toán', 'natural_sciences'),
  ('NGU_VAN', 'Ngữ văn', 'languages'),
  ('TIENG_ANH', 'Tiếng Anh', 'languages'),
  ('VAT_LY', 'Vật lý', 'natural_sciences'),
  ('HOA_HOC', 'Hóa học', 'natural_sciences'),
  ('SINH_HOC', 'Sinh học', 'natural_sciences'),
  ('LICH_SU', 'Lịch sử', 'social_sciences'),
  ('DIA_LY', 'Địa lý', 'social_sciences'),
  ('GDKT_PL', 'Giáo dục kinh tế và pháp luật', 'social_sciences'),
  ('TIN_HOC', 'Tin học', 'technology_arts'),
  ('CONG_NGHE', 'Công nghệ', 'technology_arts'),
  ('GDTC', 'Giáo dục thể chất', 'physical_education'),
  ('GDQP_AN', 'Giáo dục quốc phòng và an ninh', 'physical_education'),
  ('HD_TN_HN', 'Hoạt động trải nghiệm, hướng nghiệp', 'other'),
  ('AM_NHAC', 'Âm nhạc', 'technology_arts'),
  ('MY_THUAT', 'Mỹ thuật', 'technology_arts')
ON CONFLICT (code) DO NOTHING;

UPDATE timetable_items item
SET subject_id = mapping.subject_id
FROM (
  SELECT subject.id AS subject_id, alias.normalized_name
  FROM subjects subject
  JOIN (
    VALUES
      ('TOAN', 'toan'),
      ('NGU_VAN', 'ngu van'),
      ('NGU_VAN', 'van'),
      ('TIENG_ANH', 'tieng anh'),
      ('TIENG_ANH', 'anh van'),
      ('TIENG_ANH', 'ngoai ngu'),
      ('VAT_LY', 'vat ly'),
      ('VAT_LY', 'ly'),
      ('HOA_HOC', 'hoa hoc'),
      ('HOA_HOC', 'hoa'),
      ('SINH_HOC', 'sinh hoc'),
      ('SINH_HOC', 'sinh'),
      ('LICH_SU', 'lich su'),
      ('LICH_SU', 'su'),
      ('DIA_LY', 'dia ly'),
      ('DIA_LY', 'dia'),
      ('GDKT_PL', 'giao duc kinh te va phap luat'),
      ('GDKT_PL', 'gdktpl'),
      ('TIN_HOC', 'tin hoc'),
      ('TIN_HOC', 'tin'),
      ('CONG_NGHE', 'cong nghe'),
      ('GDTC', 'giao duc the chat'),
      ('GDTC', 'the duc'),
      ('GDQP_AN', 'giao duc quoc phong va an ninh'),
      ('GDQP_AN', 'gdqp-an'),
      ('GDQP_AN', 'quoc phong'),
      ('HD_TN_HN', 'hoat dong trai nghiem, huong nghiep'),
      ('HD_TN_HN', 'hoat dong trai nghiem huong nghiep'),
      ('AM_NHAC', 'am nhac'),
      ('MY_THUAT', 'my thuat')
  ) AS alias(code, normalized_name) ON alias.code = subject.code
) mapping
WHERE item.subject_id IS NULL
  AND lower(unaccent(btrim(item.subject_name))) = mapping.normalized_name;

WITH unmatched AS (
  SELECT
    lower(unaccent(btrim(subject_name))) AS normalized_name,
    MIN(btrim(subject_name)) AS display_name
  FROM timetable_items
  WHERE subject_id IS NULL
    AND btrim(subject_name) <> ''
  GROUP BY lower(unaccent(btrim(subject_name)))
)
INSERT INTO subjects (code, name, subject_group, is_active, description)
SELECT
  'LEGACY_' || upper(substr(md5(normalized_name), 1, 12)),
  display_name,
  'other',
  FALSE,
  'Imported from legacy timetable; requires admin review'
FROM unmatched
ON CONFLICT (code) DO NOTHING;

UPDATE timetable_items item
SET subject_id = subject.id
FROM subjects subject
WHERE item.subject_id IS NULL
  AND subject.code =
    'LEGACY_' || upper(substr(md5(lower(unaccent(btrim(item.subject_name)))), 1, 12));

