DO $$
BEGIN
  CREATE TYPE student_enrollment_status AS ENUM (
    'active',
    'transferred',
    'reserved',
    'withdrawn',
    'graduated'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE student_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
  academic_year_id BIGINT NOT NULL REFERENCES academic_years(id) ON DELETE RESTRICT,
  status student_enrollment_status NOT NULL DEFAULT 'active',
  enrolled_at DATE NOT NULL DEFAULT CURRENT_DATE,
  ended_at DATE,
  previous_enrollment_id BIGINT REFERENCES student_enrollments(id) ON DELETE SET NULL,
  note TEXT,
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (
    (status = 'active' AND ended_at IS NULL)
    OR
    (status <> 'active' AND ended_at IS NOT NULL)
  ),
  CHECK (ended_at IS NULL OR ended_at >= enrolled_at)
);

CREATE INDEX idx_student_enrollments_student_history
  ON student_enrollments(student_user_id, academic_year_id, created_at DESC);

CREATE INDEX idx_student_enrollments_classroom_status
  ON student_enrollments(classroom_id, status);

CREATE INDEX idx_student_enrollments_academic_year_status
  ON student_enrollments(academic_year_id, status);

CREATE UNIQUE INDEX uq_student_enrollments_one_active_per_year
  ON student_enrollments(student_user_id, academic_year_id)
  WHERE status = 'active';

CREATE TRIGGER trg_student_enrollments_updated_at
BEFORE UPDATE ON student_enrollments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

WITH ranked_memberships AS (
  SELECT
    cm.user_id AS student_user_id,
    cm.classroom_id,
    c.academic_year_id,
    cm.created_at::DATE AS enrolled_at,
    ROW_NUMBER() OVER (
      PARTITION BY cm.user_id, c.academic_year_id
      ORDER BY c.is_active DESC, cm.created_at DESC, cm.id DESC
    ) AS priority
  FROM classroom_members cm
  JOIN classrooms c ON c.id = cm.classroom_id
  WHERE cm.role = 'student'
    AND c.academic_year_id IS NOT NULL
)
INSERT INTO student_enrollments (
  student_user_id,
  classroom_id,
  academic_year_id,
  status,
  enrolled_at,
  ended_at,
  note
)
SELECT
  student_user_id,
  classroom_id,
  academic_year_id,
  CASE
    WHEN priority = 1 THEN 'active'::student_enrollment_status
    ELSE 'transferred'::student_enrollment_status
  END,
  enrolled_at,
  CASE WHEN priority = 1 THEN NULL ELSE enrolled_at END,
  CASE
    WHEN priority = 1 THEN 'Backfilled from classroom_members'
    ELSE 'Backfill conflict: preserved as transferred history'
  END
FROM ranked_memberships;

CREATE OR REPLACE FUNCTION prevent_student_enrollment_identity_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.student_user_id <> OLD.student_user_id
    OR NEW.classroom_id <> OLD.classroom_id
    OR NEW.academic_year_id <> OLD.academic_year_id
  THEN
    RAISE EXCEPTION
      'Enrollment identity is immutable; create a transfer record instead';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_student_enrollment_identity_immutable
BEFORE UPDATE ON student_enrollments
FOR EACH ROW EXECUTE FUNCTION prevent_student_enrollment_identity_change();

CREATE OR REPLACE FUNCTION sync_student_enrollment_compatibility()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  affected_user_id BIGINT;
  affected_academic_year_id BIGINT;
BEGIN
  affected_user_id := CASE
    WHEN TG_OP = 'DELETE' THEN OLD.student_user_id
    ELSE NEW.student_user_id
  END;
  affected_academic_year_id := CASE
    WHEN TG_OP = 'DELETE' THEN OLD.academic_year_id
    ELSE NEW.academic_year_id
  END;

  DELETE FROM classroom_members cm
  USING classrooms c
  WHERE cm.classroom_id = c.id
    AND cm.user_id = affected_user_id
    AND cm.role = 'student'
    AND c.academic_year_id = affected_academic_year_id;

  INSERT INTO classroom_members (classroom_id, user_id, role)
  SELECT enrollment.classroom_id, enrollment.student_user_id, 'student'
  FROM student_enrollments enrollment
  WHERE enrollment.student_user_id = affected_user_id
    AND enrollment.academic_year_id = affected_academic_year_id
    AND enrollment.status = 'active'
  ON CONFLICT (classroom_id, user_id, role) DO NOTHING;

  UPDATE student_profiles profile
  SET class_name = (
    SELECT classroom.name
    FROM student_enrollments enrollment
    JOIN classrooms classroom ON classroom.id = enrollment.classroom_id
    JOIN academic_years academic_year
      ON academic_year.id = enrollment.academic_year_id
    WHERE enrollment.student_user_id = affected_user_id
      AND enrollment.status = 'active'
    ORDER BY academic_year.start_date DESC, enrollment.created_at DESC
    LIMIT 1
  )
  WHERE profile.user_id = affected_user_id;

  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

CREATE TRIGGER trg_sync_student_enrollment_compatibility
AFTER INSERT OR UPDATE OF status OR DELETE ON student_enrollments
FOR EACH ROW EXECUTE FUNCTION sync_student_enrollment_compatibility();

DELETE FROM classroom_members WHERE role = 'student';

INSERT INTO classroom_members (classroom_id, user_id, role)
SELECT classroom_id, student_user_id, 'student'
FROM student_enrollments
WHERE status = 'active'
ON CONFLICT (classroom_id, user_id, role) DO NOTHING;

UPDATE student_profiles profile
SET class_name = current_enrollment.classroom_name
FROM (
  SELECT DISTINCT ON (enrollment.student_user_id)
    enrollment.student_user_id,
    classroom.name AS classroom_name
  FROM student_enrollments enrollment
  JOIN classrooms classroom ON classroom.id = enrollment.classroom_id
  JOIN academic_years academic_year
    ON academic_year.id = enrollment.academic_year_id
  WHERE enrollment.status = 'active'
  ORDER BY
    enrollment.student_user_id,
    academic_year.start_date DESC,
    enrollment.created_at DESC
) current_enrollment
WHERE profile.user_id = current_enrollment.student_user_id;
