DO $$
BEGIN
  CREATE TYPE teaching_assignment_role AS ENUM ('primary', 'assistant');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE teaching_assignment_status AS ENUM ('active', 'inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE teaching_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
  role teaching_assignment_role NOT NULL DEFAULT 'primary',
  status teaching_assignment_status NOT NULL DEFAULT 'active',
  assigned_at DATE NOT NULL,
  ended_at DATE,
  note TEXT,
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (
    (status = 'active' AND ended_at IS NULL)
    OR
    (status = 'inactive' AND ended_at IS NOT NULL)
  ),
  CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);

CREATE UNIQUE INDEX uq_teaching_assignments_active_exact
  ON teaching_assignments(
    teacher_user_id,
    classroom_id,
    subject_id,
    semester_id
  )
  WHERE status = 'active';

CREATE INDEX idx_teaching_assignments_teacher_period
  ON teaching_assignments(teacher_user_id, semester_id, status);

CREATE INDEX idx_teaching_assignments_class_subject
  ON teaching_assignments(classroom_id, subject_id, semester_id, status);

CREATE TRIGGER trg_teaching_assignments_updated_at
BEFORE UPDATE ON teaching_assignments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION validate_teaching_assignment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  classroom_year_id BIGINT;
  classroom_grade INTEGER;
  classroom_active BOOLEAN;
  semester_year_id BIGINT;
  semester_start DATE;
  semester_end DATE;
  teacher_is_valid BOOLEAN;
  curriculum_is_valid BOOLEAN;
BEGIN
  SELECT academic_year_id, grade_level, is_active
  INTO classroom_year_id, classroom_grade, classroom_active
  FROM classrooms
  WHERE id = NEW.classroom_id;

  SELECT academic_year_id, start_date, end_date
  INTO semester_year_id, semester_start, semester_end
  FROM semesters
  WHERE id = NEW.semester_id;

  SELECT EXISTS (
    SELECT 1
    FROM users user_record
    JOIN user_roles user_role ON user_role.user_id = user_record.id
    JOIN roles role_record ON role_record.id = user_role.role_id
    WHERE user_record.id = NEW.teacher_user_id
      AND user_record.status = 'active'
      AND role_record.name = 'teacher'
  )
  INTO teacher_is_valid;

  SELECT EXISTS (
    SELECT 1
    FROM curriculum_subjects curriculum
    JOIN subjects subject ON subject.id = curriculum.subject_id
    WHERE curriculum.academic_year_id = classroom_year_id
      AND curriculum.grade_level = classroom_grade
      AND curriculum.subject_id = NEW.subject_id
      AND curriculum.is_active = TRUE
      AND subject.is_active = TRUE
  )
  INTO curriculum_is_valid;

  IF classroom_year_id IS NULL OR classroom_grade IS NULL THEN
    RAISE EXCEPTION 'Classroom must have academic year and grade level';
  END IF;
  IF NOT classroom_active AND NEW.status = 'active' THEN
    RAISE EXCEPTION 'Inactive classroom cannot receive an active assignment';
  END IF;
  IF semester_year_id IS NULL OR semester_year_id <> classroom_year_id THEN
    RAISE EXCEPTION 'Semester and classroom must belong to the same academic year';
  END IF;
  IF NOT teacher_is_valid THEN
    RAISE EXCEPTION 'Teacher must be an active user with teacher role';
  END IF;
  IF NOT curriculum_is_valid THEN
    RAISE EXCEPTION 'Subject is not active in the classroom curriculum';
  END IF;
  IF NEW.assigned_at < semester_start OR NEW.assigned_at > semester_end THEN
    RAISE EXCEPTION 'assigned_at must be inside the semester';
  END IF;
  IF NEW.ended_at IS NOT NULL
    AND (NEW.ended_at < semester_start OR NEW.ended_at > semester_end)
  THEN
    RAISE EXCEPTION 'ended_at must be inside the semester';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_teaching_assignment
BEFORE INSERT OR UPDATE ON teaching_assignments
FOR EACH ROW EXECUTE FUNCTION validate_teaching_assignment();

CREATE OR REPLACE FUNCTION prevent_teaching_assignment_identity_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.teacher_user_id <> OLD.teacher_user_id
    OR NEW.classroom_id <> OLD.classroom_id
    OR NEW.subject_id <> OLD.subject_id
    OR NEW.semester_id <> OLD.semester_id
  THEN
    RAISE EXCEPTION
      'Teaching assignment identity is immutable; create a new assignment';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_teaching_assignment_identity_immutable
BEFORE UPDATE ON teaching_assignments
FOR EACH ROW EXECUTE FUNCTION prevent_teaching_assignment_identity_change();

-- Existing timetable data is evidence that a subject belongs to the class
-- curriculum. Add only missing entries and leave them optional for admin review.
INSERT INTO curriculum_subjects (
  academic_year_id,
  subject_id,
  grade_level,
  periods_per_week,
  is_required,
  is_active
)
SELECT
  classroom.academic_year_id,
  item.subject_id,
  classroom.grade_level,
  GREATEST(COUNT(*)::NUMERIC, 1),
  FALSE,
  TRUE
FROM timetable_items item
JOIN timetables timetable ON timetable.id = item.timetable_id
JOIN classrooms classroom ON classroom.id = timetable.classroom_id
JOIN subjects subject ON subject.id = item.subject_id
WHERE classroom.academic_year_id IS NOT NULL
  AND classroom.grade_level BETWEEN 10 AND 12
  AND item.subject_id IS NOT NULL
  AND subject.is_active = TRUE
GROUP BY classroom.academic_year_id, item.subject_id, classroom.grade_level
ON CONFLICT (academic_year_id, subject_id, grade_level) DO NOTHING;

WITH exact_teacher_matches AS (
  SELECT DISTINCT
    user_record.id AS teacher_user_id,
    timetable.classroom_id,
    item.subject_id,
    timetable.semester_id,
    semester.start_date AS assigned_at,
    CASE
      WHEN semester.status = 'closed'
        THEN 'inactive'::teaching_assignment_status
      ELSE 'active'::teaching_assignment_status
    END AS status,
    CASE WHEN semester.status = 'closed' THEN semester.end_date ELSE NULL END
      AS ended_at
  FROM timetable_items item
  JOIN timetables timetable ON timetable.id = item.timetable_id
  JOIN semesters semester ON semester.id = timetable.semester_id
  JOIN classrooms classroom ON classroom.id = timetable.classroom_id
  JOIN users user_record
    ON lower(unaccent(btrim(user_record.full_name))) =
       lower(unaccent(btrim(item.teacher_name)))
  JOIN user_roles user_role ON user_role.user_id = user_record.id
  JOIN roles role_record
    ON role_record.id = user_role.role_id AND role_record.name = 'teacher'
  JOIN curriculum_subjects curriculum
    ON curriculum.academic_year_id = classroom.academic_year_id
    AND curriculum.grade_level = classroom.grade_level
    AND curriculum.subject_id = item.subject_id
    AND curriculum.is_active = TRUE
  WHERE item.subject_id IS NOT NULL
    AND timetable.semester_id IS NOT NULL
    AND NULLIF(btrim(item.teacher_name), '') IS NOT NULL
    AND user_record.status = 'active'
)
INSERT INTO teaching_assignments (
  teacher_user_id,
  classroom_id,
  subject_id,
  semester_id,
  role,
  status,
  assigned_at,
  ended_at,
  note
)
SELECT
  teacher_user_id,
  classroom_id,
  subject_id,
  semester_id,
  'primary',
  status,
  assigned_at,
  ended_at,
  'Backfilled from exact timetable teacher name match'
FROM exact_teacher_matches
ON CONFLICT (
  teacher_user_id,
  classroom_id,
  subject_id,
  semester_id
) WHERE status = 'active' DO NOTHING;

ALTER TABLE timetable_items
  ADD COLUMN teaching_assignment_id BIGINT
    REFERENCES teaching_assignments(id) ON DELETE RESTRICT;

CREATE INDEX idx_timetable_items_teaching_assignment
  ON timetable_items(teaching_assignment_id);

UPDATE timetable_items item
SET teaching_assignment_id = assignment.id
FROM timetables timetable, teaching_assignments assignment, users teacher
WHERE timetable.id = item.timetable_id
  AND assignment.classroom_id = timetable.classroom_id
  AND assignment.semester_id = timetable.semester_id
  AND assignment.subject_id = item.subject_id
  AND teacher.id = assignment.teacher_user_id
  AND lower(unaccent(btrim(teacher.full_name))) =
      lower(unaccent(btrim(item.teacher_name)));
