DO $$
BEGIN
  CREATE TYPE assessment_configuration_status AS ENUM (
    'draft',
    'active',
    'archived'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE assessment_rounding_mode AS ENUM (
    'half_up',
    'half_even',
    'truncate'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE assessment_configurations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
  grade_level INTEGER NOT NULL CHECK (grade_level BETWEEN 10 AND 12),
  version INTEGER NOT NULL CHECK (version > 0),
  title VARCHAR(255) NOT NULL,
  score_scale NUMERIC(6, 2) NOT NULL DEFAULT 10
    CHECK (score_scale > 0 AND score_scale <= 100),
  decimal_places SMALLINT NOT NULL DEFAULT 1
    CHECK (decimal_places BETWEEN 0 AND 2),
  rounding_mode assessment_rounding_mode NOT NULL DEFAULT 'half_up',
  status assessment_configuration_status NOT NULL DEFAULT 'draft',
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  activated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (subject_id, semester_id, grade_level, version),
  CHECK (
    (status = 'active' AND activated_at IS NOT NULL)
    OR status <> 'active'
  )
);

CREATE TABLE assessment_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  configuration_id BIGINT NOT NULL
    REFERENCES assessment_configurations(id) ON DELETE CASCADE,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(150) NOT NULL,
  weight_percent NUMERIC(5, 2) NOT NULL
    CHECK (weight_percent > 0 AND weight_percent <= 100),
  coefficient NUMERIC(5, 2) NOT NULL DEFAULT 1
    CHECK (coefficient > 0 AND coefficient <= 20),
  max_entries SMALLINT NOT NULL DEFAULT 1
    CHECK (max_entries BETWEEN 1 AND 20),
  score_scale NUMERIC(6, 2) NOT NULL DEFAULT 10
    CHECK (score_scale > 0 AND score_scale <= 100),
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (configuration_id, code)
);

CREATE UNIQUE INDEX uq_assessment_configurations_active_scope
  ON assessment_configurations(subject_id, semester_id, grade_level)
  WHERE status = 'active';

CREATE UNIQUE INDEX uq_assessment_configurations_draft_scope
  ON assessment_configurations(subject_id, semester_id, grade_level)
  WHERE status = 'draft';

CREATE INDEX idx_assessment_configurations_scope_status
  ON assessment_configurations(
    semester_id,
    grade_level,
    subject_id,
    status,
    version DESC
  );

CREATE INDEX idx_assessment_categories_configuration_order
  ON assessment_categories(configuration_id, sort_order, id);

CREATE TRIGGER trg_assessment_configurations_updated_at
BEFORE UPDATE ON assessment_configurations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_assessment_categories_updated_at
BEFORE UPDATE ON assessment_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION validate_assessment_configuration_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  semester_year_id BIGINT;
  curriculum_exists BOOLEAN;
BEGIN
  SELECT academic_year_id
  INTO semester_year_id
  FROM semesters
  WHERE id = NEW.semester_id;

  SELECT EXISTS (
    SELECT 1
    FROM curriculum_subjects curriculum
    JOIN subjects subject ON subject.id = curriculum.subject_id
    WHERE curriculum.academic_year_id = semester_year_id
      AND curriculum.grade_level = NEW.grade_level
      AND curriculum.subject_id = NEW.subject_id
      AND curriculum.is_active = TRUE
      AND subject.is_active = TRUE
  )
  INTO curriculum_exists;

  IF semester_year_id IS NULL THEN
    RAISE EXCEPTION 'Assessment configuration semester does not exist';
  END IF;
  IF NOT curriculum_exists THEN
    RAISE EXCEPTION
      'Assessment configuration subject is not active in the curriculum';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_assessment_configuration_scope
BEFORE INSERT OR UPDATE OF subject_id, semester_id, grade_level
ON assessment_configurations
FOR EACH ROW EXECUTE FUNCTION validate_assessment_configuration_scope();

CREATE OR REPLACE FUNCTION protect_assessment_configuration_history()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.subject_id <> OLD.subject_id
    OR NEW.semester_id <> OLD.semester_id
    OR NEW.grade_level <> OLD.grade_level
    OR NEW.version <> OLD.version
  THEN
    RAISE EXCEPTION
      'Assessment configuration identity is immutable; create a new version';
  END IF;

  IF OLD.status <> 'draft' AND (
    NEW.title <> OLD.title
    OR NEW.score_scale <> OLD.score_scale
    OR NEW.decimal_places <> OLD.decimal_places
    OR NEW.rounding_mode <> OLD.rounding_mode
  ) THEN
    RAISE EXCEPTION
      'Published assessment configuration content is immutable';
  END IF;

  IF OLD.status = 'archived' AND NEW.status <> 'archived' THEN
    RAISE EXCEPTION
      'Archived assessment configuration cannot be reactivated';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_protect_assessment_configuration_history
BEFORE UPDATE ON assessment_configurations
FOR EACH ROW EXECUTE FUNCTION protect_assessment_configuration_history();

CREATE OR REPLACE FUNCTION ensure_assessment_category_is_writable()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  target_configuration_id BIGINT;
  configuration_status assessment_configuration_status;
BEGIN
  target_configuration_id := COALESCE(NEW.configuration_id, OLD.configuration_id);

  SELECT status
  INTO configuration_status
  FROM assessment_configurations
  WHERE id = target_configuration_id;

  IF configuration_status IS NOT NULL AND configuration_status <> 'draft' THEN
    RAISE EXCEPTION
      'Assessment categories are immutable after configuration activation';
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_assessment_category_writable
BEFORE INSERT OR UPDATE OR DELETE ON assessment_categories
FOR EACH ROW EXECUTE FUNCTION ensure_assessment_category_is_writable();

CREATE OR REPLACE FUNCTION validate_assessment_category_weights()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  target_configuration_id BIGINT;
  category_count INTEGER;
  total_weight NUMERIC(7, 2);
BEGIN
  target_configuration_id := COALESCE(NEW.configuration_id, OLD.configuration_id);

  IF NOT EXISTS (
    SELECT 1 FROM assessment_configurations
    WHERE id = target_configuration_id
  ) THEN
    RETURN NULL;
  END IF;

  SELECT COUNT(*), COALESCE(SUM(weight_percent), 0)
  INTO category_count, total_weight
  FROM assessment_categories
  WHERE configuration_id = target_configuration_id;

  IF category_count = 0 OR total_weight <> 100.00 THEN
    RAISE EXCEPTION
      'Assessment category weights must total exactly 100 percent';
  END IF;

  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_assessment_category_weight_total
AFTER INSERT OR UPDATE OR DELETE ON assessment_categories
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_assessment_category_weights();
