DO $$
BEGIN
  CREATE TYPE attendance_status AS ENUM (
    'present',
    'excused',
    'unexcused',
    'late'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE attendance_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE RESTRICT,
  teaching_assignment_id BIGINT
    REFERENCES teaching_assignments(id) ON DELETE RESTRICT,
  session_date DATE NOT NULL,
  lesson_index INTEGER NOT NULL DEFAULT 0,
  title VARCHAR(255),
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (lesson_index BETWEEN 0 AND 20)
);

CREATE UNIQUE INDEX uq_attendance_session_scope
  ON attendance_sessions (
    classroom_id,
    semester_id,
    session_date,
    lesson_index,
    COALESCE(subject_id, 0)
  );

CREATE INDEX idx_attendance_sessions_classroom_date
  ON attendance_sessions(classroom_id, session_date DESC);

CREATE INDEX idx_attendance_sessions_assignment
  ON attendance_sessions(teaching_assignment_id)
  WHERE teaching_assignment_id IS NOT NULL;

CREATE TABLE attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL
    REFERENCES attendance_sessions(id) ON DELETE CASCADE,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  status attendance_status NOT NULL DEFAULT 'present',
  note VARCHAR(500),
  recorded_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (session_id, student_user_id)
);

CREATE INDEX idx_attendance_records_student
  ON attendance_records(student_user_id, session_id);

CREATE INDEX idx_attendance_records_session_status
  ON attendance_records(session_id, status);

CREATE TABLE attendance_record_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_record_id BIGINT
    REFERENCES attendance_records(id) ON DELETE SET NULL,
  session_id BIGINT NOT NULL
    REFERENCES attendance_sessions(id) ON DELETE CASCADE,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  old_status attendance_status,
  new_status attendance_status NOT NULL,
  old_note VARCHAR(500),
  new_note VARCHAR(500),
  reason VARCHAR(500),
  changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_attendance_audits_session
  ON attendance_record_audits(session_id, changed_at DESC);

CREATE INDEX idx_attendance_audits_student
  ON attendance_record_audits(student_user_id, changed_at DESC);

CREATE TRIGGER trg_attendance_sessions_updated_at
BEFORE UPDATE ON attendance_sessions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_attendance_records_updated_at
BEFORE UPDATE ON attendance_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION validate_attendance_session_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  classroom_year_id BIGINT;
  semester_year_id BIGINT;
  semester_start DATE;
  semester_end DATE;
  assignment_matches BOOLEAN;
BEGIN
  SELECT academic_year_id
  INTO classroom_year_id
  FROM classrooms
  WHERE id = NEW.classroom_id;

  SELECT academic_year_id, start_date, end_date
  INTO semester_year_id, semester_start, semester_end
  FROM semesters
  WHERE id = NEW.semester_id;

  IF classroom_year_id IS NULL OR semester_year_id <> classroom_year_id THEN
    RAISE EXCEPTION 'Attendance semester must belong to the classroom academic year';
  END IF;
  IF NEW.session_date < semester_start OR NEW.session_date > semester_end THEN
    RAISE EXCEPTION 'Attendance date must be inside the semester';
  END IF;

  IF NEW.teaching_assignment_id IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1
      FROM teaching_assignments assignment
      WHERE assignment.id = NEW.teaching_assignment_id
        AND assignment.classroom_id = NEW.classroom_id
        AND assignment.semester_id = NEW.semester_id
        AND assignment.subject_id = NEW.subject_id
    )
    INTO assignment_matches;
    IF NOT assignment_matches THEN
      RAISE EXCEPTION 'Attendance teaching assignment does not match session scope';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_attendance_session_scope
BEFORE INSERT OR UPDATE ON attendance_sessions
FOR EACH ROW EXECUTE FUNCTION validate_attendance_session_scope();

