DO $$
BEGIN
  CREATE TYPE assignment_status AS ENUM ('draft', 'published', 'closed');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE assignment_submission_status AS ENUM (
    'submitted',
    'late',
    'withdrawn'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
  teaching_assignment_id BIGINT NOT NULL
    REFERENCES teaching_assignments(id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  due_at TIMESTAMPTZ NOT NULL,
  allow_late BOOLEAN NOT NULL DEFAULT FALSE,
  status assignment_status NOT NULL DEFAULT 'draft',
  published_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (
    (status = 'draft' AND published_at IS NULL AND closed_at IS NULL)
    OR (status = 'published' AND published_at IS NOT NULL AND closed_at IS NULL)
    OR (status = 'closed' AND published_at IS NOT NULL AND closed_at IS NOT NULL)
  )
);

CREATE INDEX idx_assignments_classroom_status_due
  ON assignments(classroom_id, status, due_at);
CREATE INDEX idx_assignments_assignment_status
  ON assignments(teaching_assignment_id, status);
CREATE INDEX idx_assignments_semester_subject
  ON assignments(semester_id, subject_id);

CREATE TABLE assignment_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
  media_file_id BIGINT REFERENCES media_files(id) ON DELETE SET NULL,
  file_url VARCHAR(500) NOT NULL,
  original_name VARCHAR(255),
  mime_type VARCHAR(150),
  size BIGINT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (size IS NULL OR size >= 0)
);

CREATE INDEX idx_assignment_attachments_assignment
  ON assignment_attachments(assignment_id, sort_order, id);

CREATE TABLE assignment_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE RESTRICT,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  status assignment_submission_status NOT NULL DEFAULT 'submitted',
  note VARCHAR(1000),
  first_submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  withdrawn_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (assignment_id, student_user_id)
);

CREATE INDEX idx_assignment_submissions_assignment_status
  ON assignment_submissions(assignment_id, status, last_submitted_at);
CREATE INDEX idx_assignment_submissions_student
  ON assignment_submissions(student_user_id, last_submitted_at DESC);

CREATE TABLE assignment_submission_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id BIGINT NOT NULL
    REFERENCES assignment_submissions(id) ON DELETE RESTRICT,
  media_file_id BIGINT REFERENCES media_files(id) ON DELETE SET NULL,
  file_url VARCHAR(500) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(150) NOT NULL,
  size BIGINT NOT NULL,
  version INTEGER NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  replaced_at TIMESTAMPTZ,
  CHECK (size >= 0),
  CHECK (version > 0),
  UNIQUE (submission_id, version)
);

CREATE UNIQUE INDEX uq_assignment_submission_active_file
  ON assignment_submission_files(submission_id)
  WHERE is_active = TRUE;

CREATE TABLE assignment_submission_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id BIGINT NOT NULL
    REFERENCES assignment_submissions(id) ON DELETE RESTRICT,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(30) NOT NULL CHECK (action IN ('submit', 'replace', 'withdraw')),
  old_status assignment_submission_status,
  new_status assignment_submission_status NOT NULL,
  old_file_id BIGINT REFERENCES assignment_submission_files(id) ON DELETE SET NULL,
  new_file_id BIGINT REFERENCES assignment_submission_files(id) ON DELETE SET NULL,
  note VARCHAR(1000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_assignment_submission_audits_submission
  ON assignment_submission_audits(submission_id, created_at DESC);

CREATE TRIGGER trg_assignments_updated_at
BEFORE UPDATE ON assignments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_assignment_submissions_updated_at
BEFORE UPDATE ON assignment_submissions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION validate_assignment_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  assignment_matches BOOLEAN;
  semester_start DATE;
  semester_end DATE;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM teaching_assignments teaching
    WHERE teaching.id = NEW.teaching_assignment_id
      AND teaching.classroom_id = NEW.classroom_id
      AND teaching.subject_id = NEW.subject_id
      AND teaching.semester_id = NEW.semester_id
  )
  INTO assignment_matches;

  SELECT start_date, end_date
  INTO semester_start, semester_end
  FROM semesters
  WHERE id = NEW.semester_id;

  IF NOT assignment_matches THEN
    RAISE EXCEPTION 'Assignment scope must match teaching assignment';
  END IF;
  IF NEW.due_at::DATE < semester_start OR NEW.due_at::DATE > semester_end THEN
    RAISE EXCEPTION 'Assignment due date must be inside the semester';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_assignment_scope
BEFORE INSERT OR UPDATE OF classroom_id, subject_id, semester_id,
  teaching_assignment_id, due_at
ON assignments
FOR EACH ROW EXECUTE FUNCTION validate_assignment_scope();
