DO $$
BEGIN
  CREATE TYPE gradebook_status AS ENUM ('draft');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE grade_score_state AS ENUM ('scored', 'absent', 'exempt');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE gradebooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teaching_assignment_id BIGINT NOT NULL UNIQUE
    REFERENCES teaching_assignments(id) ON DELETE RESTRICT,
  assessment_configuration_id BIGINT NOT NULL
    REFERENCES assessment_configurations(id) ON DELETE RESTRICT,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
  status gradebook_status NOT NULL DEFAULT 'draft',
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gradebook_columns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gradebook_id BIGINT NOT NULL REFERENCES gradebooks(id) ON DELETE CASCADE,
  assessment_category_id BIGINT NOT NULL
    REFERENCES assessment_categories(id) ON DELETE RESTRICT,
  category_code VARCHAR(50) NOT NULL,
  category_name VARCHAR(150) NOT NULL,
  entry_index SMALLINT NOT NULL CHECK (entry_index > 0),
  label VARCHAR(150) NOT NULL,
  max_score NUMERIC(6, 2) NOT NULL CHECK (max_score > 0),
  weight_percent NUMERIC(5, 2) NOT NULL
    CHECK (weight_percent > 0 AND weight_percent <= 100),
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (gradebook_id, assessment_category_id, entry_index)
);

CREATE TABLE student_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gradebook_id BIGINT NOT NULL REFERENCES gradebooks(id) ON DELETE RESTRICT,
  column_id BIGINT NOT NULL REFERENCES gradebook_columns(id) ON DELETE RESTRICT,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  state grade_score_state NOT NULL DEFAULT 'scored',
  score NUMERIC(6, 2),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (gradebook_id, column_id, student_user_id),
  CHECK (
    (state = 'scored' AND score IS NOT NULL AND score >= 0)
    OR (state IN ('absent', 'exempt') AND score IS NULL)
  )
);

CREATE TABLE student_score_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_score_id BIGINT REFERENCES student_scores(id) ON DELETE SET NULL,
  gradebook_id BIGINT NOT NULL REFERENCES gradebooks(id) ON DELETE RESTRICT,
  column_id BIGINT NOT NULL REFERENCES gradebook_columns(id) ON DELETE RESTRICT,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(20) NOT NULL CHECK (action IN ('insert', 'update')),
  old_state grade_score_state,
  new_state grade_score_state NOT NULL,
  old_score NUMERIC(6, 2),
  new_score NUMERIC(6, 2),
  old_version INTEGER,
  new_version INTEGER NOT NULL,
  reason VARCHAR(500),
  changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_gradebooks_scope
  ON gradebooks(classroom_id, subject_id, semester_id, status);
CREATE INDEX idx_gradebook_columns_order
  ON gradebook_columns(gradebook_id, sort_order, id);
CREATE INDEX idx_student_scores_gradebook_student
  ON student_scores(gradebook_id, student_user_id);
CREATE INDEX idx_student_score_audits_gradebook
  ON student_score_audits(gradebook_id, changed_at DESC);
CREATE INDEX idx_student_score_audits_student
  ON student_score_audits(student_user_id, changed_at DESC);

CREATE TRIGGER trg_gradebooks_updated_at
BEFORE UPDATE ON gradebooks
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_student_scores_updated_at
BEFORE UPDATE ON student_scores
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION validate_gradebook_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  assignment_record teaching_assignments%ROWTYPE;
  configuration_record assessment_configurations%ROWTYPE;
  classroom_grade INTEGER;
BEGIN
  SELECT * INTO assignment_record
  FROM teaching_assignments
  WHERE id = NEW.teaching_assignment_id;

  SELECT * INTO configuration_record
  FROM assessment_configurations
  WHERE id = NEW.assessment_configuration_id;

  SELECT grade_level INTO classroom_grade
  FROM classrooms
  WHERE id = NEW.classroom_id;

  IF assignment_record.id IS NULL OR assignment_record.status <> 'active' THEN
    RAISE EXCEPTION 'Gradebook requires an active teaching assignment';
  END IF;
  IF configuration_record.id IS NULL
    OR configuration_record.status <> 'active'
  THEN
    RAISE EXCEPTION 'Gradebook requires an active assessment configuration';
  END IF;
  IF assignment_record.classroom_id <> NEW.classroom_id
    OR assignment_record.subject_id <> NEW.subject_id
    OR assignment_record.semester_id <> NEW.semester_id
  THEN
    RAISE EXCEPTION 'Gradebook scope does not match teaching assignment';
  END IF;
  IF configuration_record.subject_id <> NEW.subject_id
    OR configuration_record.semester_id <> NEW.semester_id
    OR configuration_record.grade_level <> classroom_grade
  THEN
    RAISE EXCEPTION 'Assessment configuration does not match gradebook scope';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_gradebook_scope
BEFORE INSERT OR UPDATE ON gradebooks
FOR EACH ROW EXECUTE FUNCTION validate_gradebook_scope();

CREATE OR REPLACE FUNCTION protect_gradebook_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.teaching_assignment_id <> OLD.teaching_assignment_id
    OR NEW.assessment_configuration_id <> OLD.assessment_configuration_id
    OR NEW.classroom_id <> OLD.classroom_id
    OR NEW.subject_id <> OLD.subject_id
    OR NEW.semester_id <> OLD.semester_id
  THEN
    RAISE EXCEPTION 'Gradebook identity is immutable';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_protect_gradebook_identity
BEFORE UPDATE ON gradebooks
FOR EACH ROW EXECUTE FUNCTION protect_gradebook_identity();

CREATE OR REPLACE FUNCTION validate_student_score_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  target_classroom_id BIGINT;
  target_semester_id BIGINT;
  semester_start DATE;
  semester_end DATE;
  column_matches BOOLEAN;
  student_matches BOOLEAN;
BEGIN
  SELECT classroom_id, semester_id
  INTO target_classroom_id, target_semester_id
  FROM gradebooks
  WHERE id = NEW.gradebook_id;

  SELECT start_date, end_date
  INTO semester_start, semester_end
  FROM semesters
  WHERE id = target_semester_id;

  SELECT EXISTS (
    SELECT 1 FROM gradebook_columns
    WHERE id = NEW.column_id AND gradebook_id = NEW.gradebook_id
  ) INTO column_matches;

  SELECT EXISTS (
    SELECT 1
    FROM student_enrollments enrollment
    JOIN users student ON student.id = enrollment.student_user_id
    WHERE enrollment.student_user_id = NEW.student_user_id
      AND enrollment.classroom_id = target_classroom_id
      AND enrollment.enrolled_at <= semester_end
      AND (
        enrollment.ended_at IS NULL
        OR enrollment.ended_at >= semester_start
      )
      AND student.status = 'active'
  ) INTO student_matches;

  IF NOT column_matches THEN
    RAISE EXCEPTION 'Score column does not belong to gradebook';
  END IF;
  IF NOT student_matches THEN
    RAISE EXCEPTION 'Student is not enrolled in gradebook classroom';
  END IF;

  IF NEW.state = 'scored' AND NEW.score > (
    SELECT max_score FROM gradebook_columns WHERE id = NEW.column_id
  ) THEN
    RAISE EXCEPTION 'Score exceeds column maximum';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_student_score_scope
BEFORE INSERT OR UPDATE ON student_scores
FOR EACH ROW EXECUTE FUNCTION validate_student_score_scope();

CREATE OR REPLACE FUNCTION round_half_even(
  input_value NUMERIC,
  decimal_places INTEGER
)
RETURNS NUMERIC
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  factor NUMERIC := power(10::NUMERIC, decimal_places);
  scaled NUMERIC := input_value * factor;
  lower_value NUMERIC := floor(scaled);
  fraction NUMERIC := scaled - lower_value;
  rounded_value NUMERIC;
BEGIN
  IF fraction = 0.5 THEN
    rounded_value := CASE
      WHEN mod(lower_value, 2) = 0 THEN lower_value
      ELSE lower_value + 1
    END;
  ELSE
    rounded_value := round(scaled);
  END IF;
  RETURN rounded_value / factor;
END;
$$;
