ALTER TYPE gradebook_status ADD VALUE IF NOT EXISTS 'submitted';
ALTER TYPE gradebook_status ADD VALUE IF NOT EXISTS 'approved';
ALTER TYPE gradebook_status ADD VALUE IF NOT EXISTS 'locked';

ALTER TABLE gradebooks
  ADD COLUMN submitted_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN submitted_at TIMESTAMPTZ,
  ADD COLUMN approved_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN approved_at TIMESTAMPTZ,
  ADD COLUMN locked_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN locked_at TIMESTAMPTZ;

CREATE TABLE gradebook_change_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gradebook_id BIGINT NOT NULL REFERENCES gradebooks(id) ON DELETE RESTRICT,
  requested_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  requested_revision INTEGER NOT NULL CHECK (requested_revision > 0),
  reason VARCHAR(500) NOT NULL CHECK (length(btrim(reason)) >= 3),
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  review_note VARCHAR(500),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (
    (status = 'pending' AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL)
    OR (status <> 'pending' AND reviewed_by_user_id IS NOT NULL
      AND reviewed_at IS NOT NULL)
  )
);

CREATE UNIQUE INDEX uq_gradebook_change_requests_pending
  ON gradebook_change_requests(gradebook_id)
  WHERE status = 'pending';

CREATE INDEX idx_gradebook_change_requests_review
  ON gradebook_change_requests(status, created_at DESC);

CREATE TABLE gradebook_workflow_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gradebook_id BIGINT NOT NULL REFERENCES gradebooks(id) ON DELETE RESTRICT,
  change_request_id BIGINT
    REFERENCES gradebook_change_requests(id) ON DELETE SET NULL,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(40) NOT NULL CHECK (action IN (
    'submit', 'approve', 'reject', 'lock',
    'change_request_create', 'change_request_approve',
    'change_request_reject'
  )),
  old_status gradebook_status NOT NULL,
  new_status gradebook_status NOT NULL,
  reason VARCHAR(500),
  revision INTEGER NOT NULL CHECK (revision > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_gradebook_workflow_audits_gradebook
  ON gradebook_workflow_audits(gradebook_id, created_at DESC, id DESC);

CREATE OR REPLACE FUNCTION ensure_gradebook_score_writable()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  target_gradebook_id BIGINT;
  target_status gradebook_status;
BEGIN
  target_gradebook_id := CASE
    WHEN TG_OP = 'DELETE' THEN OLD.gradebook_id
    ELSE NEW.gradebook_id
  END;
  SELECT status INTO target_status
  FROM gradebooks
  WHERE id = target_gradebook_id;

  IF target_status IS DISTINCT FROM 'draft'::gradebook_status THEN
    RAISE EXCEPTION 'Scores can only be changed while gradebook is draft';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

CREATE TRIGGER trg_gradebook_score_writable
BEFORE INSERT OR UPDATE OR DELETE ON student_scores
FOR EACH ROW EXECUTE FUNCTION ensure_gradebook_score_writable();

CREATE OR REPLACE FUNCTION protect_gradebook_status_transition()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.status = OLD.status THEN
    RETURN NEW;
  END IF;
  IF OLD.status = 'draft' AND NEW.status = 'submitted' THEN
    RETURN NEW;
  END IF;
  IF OLD.status = 'submitted' AND NEW.status IN ('draft', 'approved') THEN
    RETURN NEW;
  END IF;
  IF OLD.status = 'approved' AND NEW.status = 'locked' THEN
    RETURN NEW;
  END IF;
  IF OLD.status = 'locked' AND NEW.status = 'draft' AND EXISTS (
    SELECT 1
    FROM gradebook_change_requests request
    WHERE request.gradebook_id = OLD.id
      AND request.status = 'approved'
      AND request.requested_revision = OLD.revision
  ) THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'Invalid gradebook status transition: % -> %',
    OLD.status, NEW.status;
END;
$$;

CREATE TRIGGER trg_protect_gradebook_status_transition
BEFORE UPDATE OF status ON gradebooks
FOR EACH ROW EXECUTE FUNCTION protect_gradebook_status_transition();

CREATE OR REPLACE FUNCTION protect_gradebook_audit_history()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF current_setting('app.allow_audit_cleanup', TRUE) = 'on' THEN
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
  END IF;
  RAISE EXCEPTION 'Gradebook audit history is immutable';
END;
$$;

CREATE TRIGGER trg_protect_student_score_audits
BEFORE UPDATE OR DELETE ON student_score_audits
FOR EACH ROW EXECUTE FUNCTION protect_gradebook_audit_history();

CREATE TRIGGER trg_protect_gradebook_workflow_audits
BEFORE UPDATE OR DELETE ON gradebook_workflow_audits
FOR EACH ROW EXECUTE FUNCTION protect_gradebook_audit_history();
