CREATE TABLE student_report_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
  academic_year_id BIGINT NOT NULL REFERENCES academic_years(id) ON DELETE RESTRICT,
  student_name VARCHAR(255) NOT NULL,
  student_code VARCHAR(50),
  classroom_name VARCHAR(100) NOT NULL,
  semester_name VARCHAR(100) NOT NULL,
  academic_year_name VARCHAR(50) NOT NULL,
  overall_average NUMERIC(6, 2),
  completed_subjects INTEGER NOT NULL DEFAULT 0 CHECK (completed_subjects >= 0),
  total_subjects INTEGER NOT NULL DEFAULT 0 CHECK (total_subjects >= 0),
  generated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (student_user_id, semester_id)
);

CREATE TABLE student_report_snapshot_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_id BIGINT NOT NULL
    REFERENCES student_report_snapshots(id) ON DELETE RESTRICT,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
  subject_code VARCHAR(50) NOT NULL,
  subject_name VARCHAR(255) NOT NULL,
  final_score NUMERIC(6, 2),
  score_scale NUMERIC(6, 2) NOT NULL DEFAULT 10 CHECK (score_scale > 0),
  gradebook_status gradebook_status NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  UNIQUE (snapshot_id, subject_id)
);

CREATE INDEX idx_report_snapshots_student_period
  ON student_report_snapshots(student_user_id, academic_year_id, semester_id);
CREATE INDEX idx_report_snapshots_classroom_period
  ON student_report_snapshots(classroom_id, semester_id);
CREATE INDEX idx_report_snapshot_subjects_order
  ON student_report_snapshot_subjects(snapshot_id, sort_order, subject_name);

CREATE OR REPLACE FUNCTION protect_report_card_snapshot()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF current_setting('app.allow_snapshot_cleanup', TRUE) = 'on' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;
  RAISE EXCEPTION 'Report card snapshots are immutable';
END;
$$;

CREATE TRIGGER trg_report_snapshots_immutable
BEFORE UPDATE OR DELETE ON student_report_snapshots
FOR EACH ROW EXECUTE FUNCTION protect_report_card_snapshot();

CREATE TRIGGER trg_report_snapshot_subjects_immutable
BEFORE UPDATE OR DELETE ON student_report_snapshot_subjects
FOR EACH ROW EXECUTE FUNCTION protect_report_card_snapshot();
