CREATE TYPE conduct_rating AS ENUM ('good', 'fair', 'pass', 'not_pass');
CREATE TYPE conduct_status AS ENUM ('draft', 'submitted', 'approved', 'locked');

CREATE TABLE student_conduct_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
  academic_year_id BIGINT NOT NULL REFERENCES academic_years(id) ON DELETE RESTRICT,
  rating conduct_rating NOT NULL,
  homeroom_comment TEXT,
  status conduct_status NOT NULL DEFAULT 'draft',
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  submitted_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  submitted_at TIMESTAMPTZ,
  approved_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  locked_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  locked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (student_user_id, semester_id)
);

CREATE INDEX idx_student_conduct_classroom_semester
  ON student_conduct_records(classroom_id, semester_id, status);
CREATE INDEX idx_student_conduct_student
  ON student_conduct_records(student_user_id, semester_id DESC);

CREATE TABLE student_conduct_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conduct_record_id BIGINT NOT NULL
    REFERENCES student_conduct_records(id) ON DELETE RESTRICT,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(20) NOT NULL CHECK (
    action IN ('create', 'edit', 'submit', 'approve', 'reject', 'lock')
  ),
  old_status conduct_status,
  new_status conduct_status NOT NULL,
  old_rating conduct_rating,
  new_rating conduct_rating NOT NULL,
  old_comment TEXT,
  new_comment TEXT,
  reason VARCHAR(500),
  revision INTEGER NOT NULL CHECK (revision > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_student_conduct_audits_record
  ON student_conduct_audits(conduct_record_id, created_at DESC, id DESC);

ALTER TABLE student_report_snapshots
  ADD COLUMN conduct_rating conduct_rating,
  ADD COLUMN homeroom_comment TEXT;

CREATE OR REPLACE FUNCTION protect_conduct_record_write()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status = 'locked'::conduct_status AND NEW IS DISTINCT FROM OLD THEN
    RAISE EXCEPTION 'Locked conduct record is immutable';
  END IF;
  IF (
    NEW.rating IS DISTINCT FROM OLD.rating
    OR NEW.homeroom_comment IS DISTINCT FROM OLD.homeroom_comment
  ) AND OLD.status <> 'draft'::conduct_status THEN
    RAISE EXCEPTION 'Conduct details can only be changed while record is draft';
  END IF;
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    IF OLD.status = 'draft'::conduct_status
      AND NEW.status = 'submitted'::conduct_status THEN
      RETURN NEW;
    END IF;
    IF OLD.status = 'submitted'::conduct_status
      AND NEW.status IN ('draft'::conduct_status, 'approved'::conduct_status) THEN
      RETURN NEW;
    END IF;
    IF OLD.status = 'approved'::conduct_status
      AND NEW.status = 'locked'::conduct_status THEN
      RETURN NEW;
    END IF;
    RAISE EXCEPTION 'Invalid conduct status transition: % -> %',
      OLD.status, NEW.status;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_protect_conduct_record_write
BEFORE UPDATE ON student_conduct_records
FOR EACH ROW EXECUTE FUNCTION protect_conduct_record_write();

CREATE OR REPLACE FUNCTION protect_conduct_audit_history()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF current_setting('app.allow_audit_cleanup', TRUE) = 'on' THEN
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
  END IF;
  RAISE EXCEPTION 'Conduct audit history is immutable';
END;
$$;

CREATE TRIGGER trg_protect_student_conduct_audits
BEFORE UPDATE OR DELETE ON student_conduct_audits
FOR EACH ROW EXECUTE FUNCTION protect_conduct_audit_history();
