DO $$
BEGIN
  CREATE TYPE guardian_link_status AS ENUM ('pending', 'verified', 'revoked');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE notification_target_role ADD VALUE IF NOT EXISTS 'guardian';

CREATE TABLE guardian_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  phone VARCHAR(50),
  address VARCHAR(500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE student_guardian_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guardian_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  relationship VARCHAR(80) NOT NULL,
  status guardian_link_status NOT NULL DEFAULT 'pending',
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
  invited_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  verified_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  revoked_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  invited_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  verified_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (guardian_user_id, student_user_id),
  CHECK (guardian_user_id <> student_user_id)
);

CREATE TABLE guardian_notification_preferences (
  guardian_user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  in_app_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  attendance_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  grades_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  conduct_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE guardian_link_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  link_id BIGINT NOT NULL REFERENCES student_guardian_links(id) ON DELETE CASCADE,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(30) NOT NULL CHECK (action IN ('invite', 'verify', 'revoke', 'reinvite')),
  old_status guardian_link_status,
  new_status guardian_link_status NOT NULL,
  reason VARCHAR(500),
  revision INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE guardian_access_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guardian_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  student_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  resource VARCHAR(40) NOT NULL CHECK (resource IN ('summary', 'attendance', 'transcript')),
  semester_id BIGINT REFERENCES semesters(id) ON DELETE SET NULL,
  accessed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_guardian_links_guardian_status
  ON student_guardian_links (guardian_user_id, status);
CREATE INDEX idx_guardian_links_student_status
  ON student_guardian_links (student_user_id, status);
CREATE INDEX idx_guardian_link_audits_link_created
  ON guardian_link_audits (link_id, created_at DESC);
CREATE INDEX idx_guardian_access_audits_guardian_created
  ON guardian_access_audits (guardian_user_id, accessed_at DESC);

CREATE TRIGGER trg_guardian_profiles_updated_at
BEFORE UPDATE ON guardian_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_student_guardian_links_updated_at
BEFORE UPDATE ON student_guardian_links
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION protect_guardian_audit_rows()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF current_setting('app.allow_guardian_audit_cleanup', TRUE) = 'on' THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION 'Guardian audit records are immutable';
END;
$$;

CREATE TRIGGER trg_guardian_link_audits_immutable
BEFORE UPDATE OR DELETE ON guardian_link_audits
FOR EACH ROW EXECUTE FUNCTION protect_guardian_audit_rows();

CREATE TRIGGER trg_guardian_access_audits_immutable
BEFORE UPDATE OR DELETE ON guardian_access_audits
FOR EACH ROW EXECUTE FUNCTION protect_guardian_audit_rows();
