DO $$
BEGIN
  CREATE TYPE timetable_status AS ENUM ('draft', 'published', 'archived');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE school_shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE bell_periods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id BIGINT NOT NULL REFERENCES school_shifts(id) ON DELETE CASCADE,
  period_index INTEGER NOT NULL CHECK (period_index BETWEEN 1 AND 20),
  starts_at TIME NOT NULL,
  ends_at TIME NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (starts_at < ends_at),
  UNIQUE (shift_id, period_index)
);

INSERT INTO school_shifts (code, name, sort_order)
VALUES
  ('morning', 'Ca sáng', 1),
  ('afternoon', 'Ca chiều', 2)
ON CONFLICT (code) DO NOTHING;

INSERT INTO bell_periods (
  shift_id, period_index, starts_at, ends_at, sort_order
)
SELECT shift.id, period.period_index, period.starts_at, period.ends_at,
  period.period_index
FROM school_shifts shift
JOIN (
  VALUES
    ('morning', 1, TIME '07:00', TIME '07:45'),
    ('morning', 2, TIME '07:50', TIME '08:35'),
    ('morning', 3, TIME '08:50', TIME '09:35'),
    ('morning', 4, TIME '09:40', TIME '10:25'),
    ('morning', 5, TIME '10:30', TIME '11:15'),
    ('afternoon', 1, TIME '13:00', TIME '13:45'),
    ('afternoon', 2, TIME '13:50', TIME '14:35'),
    ('afternoon', 3, TIME '14:50', TIME '15:35'),
    ('afternoon', 4, TIME '15:40', TIME '16:25'),
    ('afternoon', 5, TIME '16:30', TIME '17:15')
) AS period(shift_code, period_index, starts_at, ends_at)
  ON period.shift_code = shift.code
ON CONFLICT (shift_id, period_index) DO NOTHING;

ALTER TABLE timetables
  ADD COLUMN status timetable_status NOT NULL DEFAULT 'draft',
  ADD COLUMN version_number INTEGER NOT NULL DEFAULT 1 CHECK (version_number > 0),
  ADD COLUMN published_at TIMESTAMPTZ,
  ADD COLUMN published_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL;

-- Existing schedules are not automatically published because legacy rows may
-- contain teacher conflicts that were never validated.
UPDATE timetables SET status = 'draft', is_active = FALSE;

WITH versions AS (
  SELECT id,
    ROW_NUMBER() OVER (
      PARTITION BY classroom_id, COALESCE(semester_id, 0)
      ORDER BY created_at, id
    ) AS version_number
  FROM timetables
)
UPDATE timetables timetable
SET version_number = versions.version_number
FROM versions
WHERE versions.id = timetable.id;

ALTER TABLE timetable_items
  ADD COLUMN shift_id BIGINT REFERENCES school_shifts(id) ON DELETE RESTRICT,
  ADD COLUMN teacher_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT;

UPDATE timetable_items
SET shift_id = (SELECT id FROM school_shifts WHERE code = 'morning')
WHERE shift_id IS NULL;

UPDATE timetable_items item
SET teacher_user_id = assignment.teacher_user_id
FROM teaching_assignments assignment
WHERE assignment.id = item.teaching_assignment_id
  AND item.teacher_user_id IS NULL;

ALTER TABLE timetable_items ALTER COLUMN shift_id SET NOT NULL;

ALTER TABLE timetable_items
  DROP CONSTRAINT IF EXISTS timetable_items_timetable_id_day_of_week_lesson_index_key;

ALTER TABLE timetable_items
  ADD CONSTRAINT uq_timetable_items_slot
  UNIQUE (timetable_id, day_of_week, shift_id, lesson_index);

CREATE UNIQUE INDEX uq_timetables_published_class_semester
  ON timetables (classroom_id, COALESCE(semester_id, 0))
  WHERE status = 'published';

CREATE INDEX idx_timetables_status_period
  ON timetables (status, academic_year_id, semester_id, updated_at DESC);

CREATE INDEX idx_timetable_items_teacher_slot
  ON timetable_items (teacher_user_id, day_of_week, shift_id, lesson_index);

CREATE INDEX idx_timetable_items_room_slot
  ON timetable_items (lower(room), day_of_week, shift_id, lesson_index)
  WHERE NULLIF(btrim(room), '') IS NOT NULL;

CREATE TRIGGER trg_school_shifts_updated_at
BEFORE UPDATE ON school_shifts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_bell_periods_updated_at
BEFORE UPDATE ON bell_periods
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION validate_timetable_item_assignment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  timetable_classroom_id BIGINT;
  timetable_semester_id BIGINT;
  assignment_teacher_id BIGINT;
  assignment_classroom_id BIGINT;
  assignment_subject_id BIGINT;
  assignment_semester_id BIGINT;
  assignment_status teaching_assignment_status;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM bell_periods
    WHERE shift_id = NEW.shift_id AND period_index = NEW.lesson_index
  ) THEN
    RAISE EXCEPTION 'TIMETABLE_INVALID_PERIOD: shift % does not contain period %',
      NEW.shift_id, NEW.lesson_index;
  END IF;

  IF NEW.teaching_assignment_id IS NULL THEN
    NEW.teacher_user_id = NULL;
    RETURN NEW;
  END IF;

  SELECT classroom_id, semester_id
  INTO timetable_classroom_id, timetable_semester_id
  FROM timetables WHERE id = NEW.timetable_id;

  SELECT teacher_user_id, classroom_id, subject_id, semester_id, status
  INTO assignment_teacher_id, assignment_classroom_id, assignment_subject_id,
    assignment_semester_id, assignment_status
  FROM teaching_assignments WHERE id = NEW.teaching_assignment_id;

  IF assignment_teacher_id IS NULL
    OR assignment_status <> 'active'
    OR assignment_classroom_id <> timetable_classroom_id
    OR assignment_semester_id IS DISTINCT FROM timetable_semester_id
    OR assignment_subject_id IS DISTINCT FROM NEW.subject_id
  THEN
    RAISE EXCEPTION 'TIMETABLE_INVALID_ASSIGNMENT: assignment does not match class, semester, and subject';
  END IF;

  NEW.teacher_user_id = assignment_teacher_id;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_timetable_item_assignment
BEFORE INSERT OR UPDATE ON timetable_items
FOR EACH ROW EXECUTE FUNCTION validate_timetable_item_assignment();

CREATE OR REPLACE FUNCTION validate_timetable_publish()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  conflicting RECORD;
BEGIN
  IF NEW.status <> 'published' THEN
    NEW.is_active = FALSE;
    IF NEW.status = 'archived' THEN
      NEW.published_at = COALESCE(NEW.published_at, OLD.published_at);
    END IF;
    RETURN NEW;
  END IF;

  IF EXISTS (
    SELECT 1 FROM timetable_items
    WHERE timetable_id = NEW.id
      AND (teaching_assignment_id IS NULL OR teacher_user_id IS NULL)
  ) THEN
    RAISE EXCEPTION 'TIMETABLE_ASSIGNMENT_REQUIRED: every published lesson needs a teaching assignment';
  END IF;

  SELECT
    current_item.day_of_week,
    current_item.lesson_index,
    shift.name AS shift_name,
    teacher.full_name AS teacher_name,
    current_item.room,
    classroom.name AS classroom_name
  INTO conflicting
  FROM timetable_items current_item
  JOIN school_shifts shift ON shift.id = current_item.shift_id
  LEFT JOIN users teacher ON teacher.id = current_item.teacher_user_id
  JOIN timetable_items other_item
    ON other_item.day_of_week = current_item.day_of_week
    AND other_item.shift_id = current_item.shift_id
    AND other_item.lesson_index = current_item.lesson_index
    AND (
      other_item.teacher_user_id = current_item.teacher_user_id
      OR (
        NULLIF(lower(btrim(other_item.room)), '') IS NOT NULL
        AND lower(btrim(other_item.room)) = lower(btrim(current_item.room))
      )
    )
  JOIN timetables other_timetable
    ON other_timetable.id = other_item.timetable_id
    AND other_timetable.id <> NEW.id
    AND other_timetable.status = 'published'
    AND other_timetable.semester_id IS NOT DISTINCT FROM NEW.semester_id
  JOIN classrooms classroom ON classroom.id = other_timetable.classroom_id
  WHERE current_item.timetable_id = NEW.id
  LIMIT 1;

  IF conflicting IS NOT NULL THEN
    RAISE EXCEPTION
      'TIMETABLE_CONFLICT: day %, %, period %, teacher %, room %, class %',
      conflicting.day_of_week,
      conflicting.shift_name,
      conflicting.lesson_index,
      COALESCE(conflicting.teacher_name, '-'),
      COALESCE(conflicting.room, '-'),
      conflicting.classroom_name;
  END IF;

  NEW.is_active = TRUE;
  NEW.published_at = COALESCE(NEW.published_at, CURRENT_TIMESTAMP);
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_timetable_publish
BEFORE INSERT OR UPDATE OF status ON timetables
FOR EACH ROW EXECUTE FUNCTION validate_timetable_publish();
