DO $$
BEGIN
  CREATE TYPE academic_calendar_entry_type AS ENUM (
    'test', 'exam', 'make_up', 'no_school', 'deadline'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE academic_calendar_entry_status AS ENUM (
    'draft', 'proposed', 'published', 'archived'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE academic_calendar_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year_id BIGINT NOT NULL REFERENCES academic_years(id) ON DELETE RESTRICT,
  semester_id BIGINT REFERENCES semesters(id) ON DELETE RESTRICT,
  entry_type academic_calendar_entry_type NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  classroom_id BIGINT REFERENCES classrooms(id) ON DELETE CASCADE,
  subject_id BIGINT REFERENCES subjects(id) ON DELETE RESTRICT,
  teaching_assignment_id BIGINT REFERENCES teaching_assignments(id) ON DELETE RESTRICT,
  teacher_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  all_day BOOLEAN NOT NULL DEFAULT FALSE,
  room VARCHAR(100),
  status academic_calendar_entry_status NOT NULL DEFAULT 'draft',
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
  created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  published_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (ends_at > starts_at),
  CHECK (
    entry_type IN ('no_school', 'deadline') OR (
      classroom_id IS NOT NULL AND subject_id IS NOT NULL
      AND teaching_assignment_id IS NOT NULL AND teacher_user_id IS NOT NULL
      AND semester_id IS NOT NULL
    )
  )
);

CREATE TABLE academic_calendar_entry_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_id BIGINT NOT NULL REFERENCES academic_calendar_entries(id) ON DELETE CASCADE,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(30) NOT NULL CHECK (action IN ('create', 'update', 'publish', 'archive')),
  revision INTEGER NOT NULL,
  old_data JSONB,
  new_data JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_academic_calendar_status_start
  ON academic_calendar_entries (status, starts_at, id);
CREATE INDEX idx_academic_calendar_class_start
  ON academic_calendar_entries (classroom_id, starts_at);
CREATE INDEX idx_academic_calendar_teacher_start
  ON academic_calendar_entries (teacher_user_id, starts_at);
CREATE INDEX idx_academic_calendar_room_start
  ON academic_calendar_entries (lower(room), starts_at)
  WHERE NULLIF(btrim(room), '') IS NOT NULL;
CREATE INDEX idx_academic_calendar_audit_entry
  ON academic_calendar_entry_audits (entry_id, revision DESC, id DESC);

CREATE TRIGGER trg_academic_calendar_entries_updated_at
BEFORE UPDATE ON academic_calendar_entries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION validate_academic_calendar_assignment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  assignment_record RECORD;
BEGIN
  IF NEW.entry_type IN ('no_school', 'deadline') THEN
    IF NEW.teaching_assignment_id IS NOT NULL THEN
      SELECT assignment.teacher_user_id, assignment.classroom_id,
        assignment.subject_id, assignment.semester_id,
        semester.academic_year_id, assignment.status
      INTO assignment_record
      FROM teaching_assignments assignment
      JOIN semesters semester ON semester.id = assignment.semester_id
      WHERE assignment.id = NEW.teaching_assignment_id;
    ELSE
      RETURN NEW;
    END IF;
  ELSE
    SELECT assignment.teacher_user_id, assignment.classroom_id,
      assignment.subject_id, assignment.semester_id,
      semester.academic_year_id, assignment.status
    INTO assignment_record
    FROM teaching_assignments assignment
    JOIN semesters semester ON semester.id = assignment.semester_id
    WHERE assignment.id = NEW.teaching_assignment_id;
  END IF;

  IF NOT FOUND OR assignment_record.status <> 'active' THEN
    RAISE EXCEPTION 'ACADEMIC_CALENDAR_INVALID_ASSIGNMENT: assignment is missing or inactive';
  END IF;
  IF NEW.teacher_user_id <> assignment_record.teacher_user_id
    OR NEW.classroom_id <> assignment_record.classroom_id
    OR NEW.subject_id <> assignment_record.subject_id
    OR NEW.semester_id <> assignment_record.semester_id
    OR NEW.academic_year_id <> assignment_record.academic_year_id
  THEN
    RAISE EXCEPTION 'ACADEMIC_CALENDAR_INVALID_ASSIGNMENT: scope does not match teaching assignment';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_academic_calendar_assignment
BEFORE INSERT OR UPDATE OF teaching_assignment_id, teacher_user_id,
  classroom_id, subject_id, semester_id, academic_year_id, entry_type
ON academic_calendar_entries
FOR EACH ROW EXECUTE FUNCTION validate_academic_calendar_assignment();

CREATE OR REPLACE FUNCTION protect_academic_calendar_audits()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'Academic calendar audit records are immutable';
END;
$$;

CREATE TRIGGER trg_academic_calendar_audits_immutable
BEFORE UPDATE OR DELETE ON academic_calendar_entry_audits
FOR EACH ROW EXECUTE FUNCTION protect_academic_calendar_audits();
