DO $$
BEGIN
  CREATE TYPE daily_schedule_override_type AS ENUM (
    'substitute', 'reschedule', 'room_change', 'cancelled'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE daily_schedule_override_status AS ENUM (
    'draft', 'proposed', 'published', 'archived'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE daily_schedule_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
  timetable_id BIGINT NOT NULL REFERENCES timetables(id) ON DELETE CASCADE,
  timetable_item_id BIGINT NOT NULL REFERENCES timetable_items(id) ON DELETE CASCADE,
  override_date DATE NOT NULL,
  override_type daily_schedule_override_type NOT NULL,
  status daily_schedule_override_status NOT NULL DEFAULT 'draft',
  substitute_teacher_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  new_day_of_week INTEGER,
  new_shift_id BIGINT REFERENCES school_shifts(id) ON DELETE RESTRICT,
  new_lesson_index INTEGER,
  room VARCHAR(100),
  reason VARCHAR(500) NOT NULL,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  approved_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (new_day_of_week IS NULL OR new_day_of_week BETWEEN 1 AND 7),
  CHECK (new_lesson_index IS NULL OR new_lesson_index BETWEEN 1 AND 20),
  CHECK (override_type <> 'substitute' OR substitute_teacher_user_id IS NOT NULL),
  CHECK (override_type <> 'room_change' OR NULLIF(BTRIM(room), '') IS NOT NULL),
  CHECK (
    override_type <> 'reschedule'
    OR (new_day_of_week IS NOT NULL AND new_shift_id IS NOT NULL AND new_lesson_index IS NOT NULL)
  )
);

CREATE UNIQUE INDEX uq_daily_schedule_override_active_item_date
  ON daily_schedule_overrides (timetable_item_id, override_date)
  WHERE status IN ('draft', 'proposed', 'published');

CREATE INDEX idx_daily_schedule_overrides_classroom_date
  ON daily_schedule_overrides (classroom_id, override_date, status);

CREATE INDEX idx_daily_schedule_overrides_substitute_date
  ON daily_schedule_overrides (substitute_teacher_user_id, override_date, status);

CREATE TABLE daily_schedule_override_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  override_id BIGINT REFERENCES daily_schedule_overrides(id) ON DELETE SET NULL,
  actor_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  action VARCHAR(30) NOT NULL CHECK (action IN ('create', 'update', 'publish', 'archive', 'delete')),
  old_data JSONB,
  new_data JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_daily_schedule_override_audits_override
  ON daily_schedule_override_audits (override_id, created_at DESC, id DESC);

CREATE OR REPLACE FUNCTION prevent_daily_schedule_override_audit_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'DAILY_SCHEDULE_OVERRIDE_AUDIT_IMMUTABLE';
END;
$$;

CREATE TRIGGER trg_daily_schedule_override_audit_immutable
BEFORE UPDATE OR DELETE ON daily_schedule_override_audits
FOR EACH ROW EXECUTE FUNCTION prevent_daily_schedule_override_audit_mutation();

CREATE TRIGGER trg_daily_schedule_overrides_updated_at
BEFORE UPDATE ON daily_schedule_overrides
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION validate_daily_schedule_override_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  timetable_classroom_id BIGINT;
  timetable_status_value timetable_status;
  item_teacher_id BIGINT;
  item_subject_id BIGINT;
  item_semester_id BIGINT;
  substitute_is_teacher BOOLEAN;
  substitute_has_assignment BOOLEAN;
BEGIN
  SELECT timetable.classroom_id, timetable.status, item.teacher_user_id,
    item.subject_id, timetable.semester_id
  INTO timetable_classroom_id, timetable_status_value, item_teacher_id,
    item_subject_id, item_semester_id
  FROM timetable_items item
  JOIN timetables timetable ON timetable.id = item.timetable_id
  WHERE item.id = NEW.timetable_item_id AND timetable.id = NEW.timetable_id;

  IF timetable_classroom_id IS NULL OR timetable_classroom_id <> NEW.classroom_id THEN
    RAISE EXCEPTION 'DAILY_OVERRIDE_INVALID_TIMETABLE_ITEM: item does not belong to timetable/classroom';
  END IF;
  IF timetable_status_value <> 'published' THEN
    RAISE EXCEPTION 'DAILY_OVERRIDE_TIMETABLE_NOT_PUBLISHED: only published timetable slots can be overridden';
  END IF;

  IF NEW.substitute_teacher_user_id IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM user_roles ur JOIN roles role ON role.id = ur.role_id
      JOIN users account ON account.id = ur.user_id
      WHERE ur.user_id = NEW.substitute_teacher_user_id
        AND role.name = 'teacher' AND account.status = 'active'
    ) INTO substitute_is_teacher;
    IF NOT substitute_is_teacher THEN
      RAISE EXCEPTION 'DAILY_OVERRIDE_SUBSTITUTE_NOT_TEACHER: substitute account is not an active teacher';
    END IF;
    IF item_subject_id IS NOT NULL AND item_semester_id IS NOT NULL THEN
      SELECT EXISTS (
        SELECT 1 FROM teaching_assignments assignment
        WHERE assignment.teacher_user_id = NEW.substitute_teacher_user_id
          AND assignment.classroom_id = NEW.classroom_id
          AND assignment.subject_id = item_subject_id
          AND assignment.semester_id = item_semester_id
          AND assignment.status = 'active'
      ) INTO substitute_has_assignment;
      IF NOT substitute_has_assignment THEN
        RAISE EXCEPTION 'DAILY_OVERRIDE_SUBSTITUTE_ASSIGNMENT_REQUIRED: substitute has no active assignment for class and subject';
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_daily_schedule_override_scope
BEFORE INSERT OR UPDATE ON daily_schedule_overrides
FOR EACH ROW EXECUTE FUNCTION validate_daily_schedule_override_scope();
