DO $$
BEGIN
  CREATE TYPE notification_priority AS ENUM ('normal', 'important', 'urgent');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE notification_target_scope AS ENUM ('school', 'role', 'grade', 'classroom', 'users');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE notifications
  ADD COLUMN IF NOT EXISTS priority notification_priority NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS target_scope notification_target_scope NOT NULL DEFAULT 'role',
  ADD COLUMN IF NOT EXISTS grade_level INTEGER,
  ADD COLUMN IF NOT EXISTS requires_acknowledgement BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(120),
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;

ALTER TABLE notifications
  ADD CONSTRAINT notifications_grade_level_check
  CHECK (grade_level IS NULL OR grade_level BETWEEN 10 AND 12);

CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_idempotency_key
  ON notifications(idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_notifications_priority_created
  ON notifications(priority, created_at DESC);

ALTER TABLE user_notifications
  ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_user_notifications_acknowledgement
  ON user_notifications(user_id, acknowledged_at)
  WHERE acknowledged_at IS NULL;

CREATE TABLE IF NOT EXISTS notification_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id BIGINT REFERENCES notifications(id) ON DELETE SET NULL,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(30) NOT NULL CHECK (action IN ('create', 'read', 'acknowledge', 'delete')),
  details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notification_audits_notification
  ON notification_audit_logs(notification_id, created_at DESC);
