DO $$
BEGIN
  CREATE TYPE teaching_plan_status AS ENUM ('draft', 'submitted', 'approved', 'rejected', 'archived');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE teaching_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teaching_assignment_id BIGINT NOT NULL UNIQUE REFERENCES teaching_assignments(id) ON DELETE RESTRICT,
  teacher_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
  academic_year_id BIGINT NOT NULL REFERENCES academic_years(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
  title VARCHAR(255) NOT NULL,
  objectives TEXT,
  content TEXT,
  resources TEXT,
  status teaching_plan_status NOT NULL DEFAULT 'draft',
  version_number INTEGER NOT NULL DEFAULT 1 CHECK (version_number > 0),
  reviewer_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  review_comment TEXT,
  submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  archived_at TIMESTAMPTZ,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_teaching_plans_teacher_status
  ON teaching_plans(teacher_user_id, status, updated_at DESC);
CREATE INDEX idx_teaching_plans_class_subject
  ON teaching_plans(classroom_id, subject_id, semester_id, status);

CREATE TABLE teaching_plan_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teaching_plan_id BIGINT NOT NULL REFERENCES teaching_plans(id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL CHECK (version_number > 0),
  title VARCHAR(255) NOT NULL,
  objectives TEXT,
  content TEXT,
  resources TEXT,
  created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(teaching_plan_id, version_number)
);

CREATE TABLE teaching_plan_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teaching_plan_id BIGINT NOT NULL REFERENCES teaching_plans(id) ON DELETE CASCADE,
  actor_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  action VARCHAR(30) NOT NULL CHECK (action IN ('create', 'update', 'submit', 'approve', 'reject', 'archive')),
  old_status teaching_plan_status,
  new_status teaching_plan_status,
  reason TEXT,
  old_data JSONB,
  new_data JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_teaching_plan_audits_plan_created
  ON teaching_plan_audits(teaching_plan_id, created_at DESC, id DESC);

CREATE OR REPLACE FUNCTION validate_teaching_plan_assignment()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  assignment_teacher BIGINT;
  assignment_classroom BIGINT;
  assignment_subject BIGINT;
  assignment_semester BIGINT;
  assignment_year BIGINT;
BEGIN
  SELECT assignment.teacher_user_id, assignment.classroom_id,
    assignment.subject_id, assignment.semester_id, classroom.academic_year_id
  INTO assignment_teacher, assignment_classroom, assignment_subject,
    assignment_semester, assignment_year
  FROM teaching_assignments assignment
  JOIN classrooms classroom ON classroom.id = assignment.classroom_id
  WHERE assignment.id = NEW.teaching_assignment_id;

  IF assignment_teacher IS NULL
    OR NEW.teacher_user_id <> assignment_teacher
    OR NEW.classroom_id <> assignment_classroom
    OR NEW.subject_id <> assignment_subject
    OR NEW.semester_id <> assignment_semester
    OR NEW.academic_year_id <> assignment_year
  THEN
    RAISE EXCEPTION 'TEACHING_PLAN_ASSIGNMENT_SCOPE_INVALID';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_teaching_plan_assignment
BEFORE INSERT OR UPDATE ON teaching_plans
FOR EACH ROW EXECUTE FUNCTION validate_teaching_plan_assignment();

CREATE OR REPLACE FUNCTION prevent_teaching_plan_approved_edit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.status = 'approved' AND (
    NEW.title IS DISTINCT FROM OLD.title OR
    NEW.objectives IS DISTINCT FROM OLD.objectives OR
    NEW.content IS DISTINCT FROM OLD.content OR
    NEW.resources IS DISTINCT FROM OLD.resources OR
    NEW.version_number IS DISTINCT FROM OLD.version_number
  ) THEN
    RAISE EXCEPTION 'APPROVED_TEACHING_PLAN_VERSION_IMMUTABLE';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_prevent_teaching_plan_approved_edit
BEFORE UPDATE ON teaching_plans
FOR EACH ROW EXECUTE FUNCTION prevent_teaching_plan_approved_edit();

CREATE TRIGGER trg_teaching_plans_updated_at
BEFORE UPDATE ON teaching_plans
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
