DO $$
BEGIN
  CREATE TYPE class_journal_status AS ENUM ('draft', 'completed', 'cancelled');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE class_journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timetable_item_id BIGINT NOT NULL REFERENCES timetable_items(id) ON DELETE RESTRICT,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE RESTRICT,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
  journal_date DATE NOT NULL,
  effective_day_of_week INTEGER NOT NULL CHECK (effective_day_of_week BETWEEN 1 AND 7),
  effective_shift_id BIGINT NOT NULL REFERENCES school_shifts(id) ON DELETE RESTRICT,
  effective_lesson_index INTEGER NOT NULL CHECK (effective_lesson_index BETWEEN 1 AND 20),
  effective_teacher_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  attendance_session_id BIGINT REFERENCES attendance_sessions(id) ON DELETE SET NULL,
  lesson_content TEXT,
  class_comment TEXT,
  progress_note TEXT,
  homework TEXT,
  status class_journal_status NOT NULL DEFAULT 'draft',
  created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (timetable_item_id, journal_date)
);

CREATE INDEX idx_class_journal_scope
  ON class_journal_entries(classroom_id, semester_id, journal_date DESC);
CREATE INDEX idx_class_journal_teacher_date
  ON class_journal_entries(effective_teacher_user_id, journal_date DESC);
CREATE INDEX idx_class_journal_status
  ON class_journal_entries(status, journal_date DESC);

CREATE TABLE class_journal_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_entry_id BIGINT NOT NULL REFERENCES class_journal_entries(id) ON DELETE CASCADE,
  actor_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  action VARCHAR(30) NOT NULL CHECK (action IN ('create', 'update', 'complete', 'cancel')),
  reason VARCHAR(500),
  old_data JSONB,
  new_data JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_class_journal_audits_entry
  ON class_journal_audits(journal_entry_id, created_at DESC, id DESC);

CREATE OR REPLACE FUNCTION validate_class_journal_scope()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  item_classroom_id BIGINT;
  item_subject_id BIGINT;
  item_semester_id BIGINT;
  semester_start DATE;
  semester_end DATE;
BEGIN
  SELECT timetable.classroom_id, item.subject_id, timetable.semester_id
  INTO item_classroom_id, item_subject_id, item_semester_id
  FROM timetable_items item
  JOIN timetables timetable ON timetable.id = item.timetable_id
  WHERE item.id = NEW.timetable_item_id;

  SELECT start_date, end_date
  INTO semester_start, semester_end
  FROM semesters
  WHERE id = NEW.semester_id;

  IF item_classroom_id IS NULL
    OR item_classroom_id <> NEW.classroom_id
    OR item_subject_id <> NEW.subject_id
    OR item_semester_id IS DISTINCT FROM NEW.semester_id
  THEN
    RAISE EXCEPTION 'CLASS_JOURNAL_SCOPE_INVALID';
  END IF;
  IF semester_start IS NULL OR NEW.journal_date < semester_start OR NEW.journal_date > semester_end THEN
    RAISE EXCEPTION 'CLASS_JOURNAL_DATE_OUTSIDE_SEMESTER';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_class_journal_scope
BEFORE INSERT OR UPDATE ON class_journal_entries
FOR EACH ROW EXECUTE FUNCTION validate_class_journal_scope();

CREATE OR REPLACE FUNCTION prevent_class_journal_identity_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.timetable_item_id <> OLD.timetable_item_id
    OR NEW.classroom_id <> OLD.classroom_id
    OR NEW.subject_id <> OLD.subject_id
    OR NEW.semester_id <> OLD.semester_id
    OR NEW.journal_date <> OLD.journal_date
    OR NEW.effective_day_of_week <> OLD.effective_day_of_week
    OR NEW.effective_shift_id <> OLD.effective_shift_id
    OR NEW.effective_lesson_index <> OLD.effective_lesson_index
    OR NEW.effective_teacher_user_id <> OLD.effective_teacher_user_id
  THEN
    RAISE EXCEPTION 'CLASS_JOURNAL_IDENTITY_IMMUTABLE';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_class_journal_identity_immutable
BEFORE UPDATE ON class_journal_entries
FOR EACH ROW EXECUTE FUNCTION prevent_class_journal_identity_change();

CREATE OR REPLACE FUNCTION prevent_class_journal_audit_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'CLASS_JOURNAL_AUDIT_IMMUTABLE';
END;
$$;

CREATE TRIGGER trg_class_journal_audit_immutable
BEFORE UPDATE OR DELETE ON class_journal_audits
FOR EACH ROW EXECUTE FUNCTION prevent_class_journal_audit_mutation();

CREATE TRIGGER trg_class_journal_updated_at
BEFORE UPDATE ON class_journal_entries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
