import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { PoolClient } from 'pg';
import { env } from '../config/env.js';
import { closeDatabasePool, postgresPool } from './postgres.js';
import { logger } from '../utils/logger.js';

type MigrationScope = 'schema' | 'seed';
type MigrationTarget = MigrationScope | 'all' | 'status';

const projectRoot = path.resolve(process.cwd(), '..');
const migrationDirectories: Record<MigrationScope, string> = {
  schema: path.join(projectRoot, 'database', 'postgresql', 'migrations'),
  seed: path.join(projectRoot, 'database', 'postgresql', 'seeds'),
};

function getTarget(value: string | undefined): MigrationTarget {
  if (value === 'schema' || value === 'seeds' || value === 'seed' || value === 'all' || value === 'status') {
    return value === 'seeds' ? 'seed' : value;
  }

  throw new Error('Invalid migration target. Use schema, seeds, all, or status.');
}

async function ensureMigrationLedger(client: PoolClient) {
  await client.query(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      scope VARCHAR(20) NOT NULL CHECK (scope IN ('schema', 'seed')),
      name VARCHAR(255) NOT NULL,
      checksum CHAR(64) NOT NULL,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE (scope, name)
    )
  `);
}

async function getSqlFiles(directory: string) {
  const entries = await fs.readdir(directory, { withFileTypes: true });

  return entries
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith('.sql'))
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right, 'en'));
}

function checksum(content: string) {
  return crypto.createHash('sha256').update(content, 'utf8').digest('hex');
}

async function runFiles(client: PoolClient, scope: MigrationScope) {
  const directory = migrationDirectories[scope];
  const files = await getSqlFiles(directory);

  if (files.length === 0) {
    logger.info({ directory, scope }, 'No SQL files found');
    return;
  }

  for (const fileName of files) {
    const filePath = path.join(directory, fileName);
    const sql = await fs.readFile(filePath, 'utf8');
    const fileChecksum = checksum(sql);
    const existing = await client.query<{ checksum: string }>(
      'SELECT checksum FROM schema_migrations WHERE scope = $1 AND name = $2',
      [scope, fileName],
    );

    if (existing.rows[0]) {
      if (existing.rows[0].checksum !== fileChecksum) {
        throw new Error(
          `Checksum mismatch for applied ${scope} file ${fileName}. Add a new migration instead of editing it.`,
        );
      }

      logger.info({ scope, fileName }, 'Skipped already applied migration');
      continue;
    }

    if (!sql.trim()) {
      logger.info({ scope, fileName }, 'Skipped empty migration');
      continue;
    }

    logger.info({ scope, fileName }, 'Running migration');
    await client.query('BEGIN');

    try {
      await client.query(sql);
      await client.query(
        `
          INSERT INTO schema_migrations (scope, name, checksum)
          VALUES ($1, $2, $3)
        `,
        [scope, fileName, fileChecksum],
      );
      await client.query('COMMIT');
      logger.info({ scope, fileName }, 'Completed migration');
    } catch (error) {
      await client.query('ROLLBACK');
      throw new Error(
        `Failed ${scope} file ${fileName}: ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    }
  }
}

async function printStatus(client: PoolClient) {
  await ensureMigrationLedger(client);
  const result = await client.query<{
    scope: MigrationScope;
    name: string;
    applied_at: Date;
  }>(
    'SELECT scope, name, applied_at FROM schema_migrations ORDER BY scope, name',
  );

  if (result.rows.length === 0) {
    logger.info('No PostgreSQL migrations have been applied.');
    return;
  }

  for (const row of result.rows) {
    logger.info(
      {
        scope: row.scope,
        name: row.name,
        appliedAt: row.applied_at.toISOString(),
      },
      'Migration status',
    );
  }
}

async function run() {
  const target = getTarget(process.argv[2] ?? 'all');
  const client = await postgresPool.connect();

  try {
    await client.query('SELECT pg_advisory_lock(hashtext($1))', [
      'thpt-pct-pt-schema-migrations',
    ]);

    if (target === 'status') {
      await printStatus(client);
      return;
    }

    await ensureMigrationLedger(client);

    if (target === 'schema' || target === 'all') {
      await runFiles(client, 'schema');
    }

    if (target === 'seed' || target === 'all') {
      await runFiles(client, 'seed');
    }

    logger.info({ database: env.database.name }, 'Database setup completed');
  } finally {
    await client.query('SELECT pg_advisory_unlock(hashtext($1))', [
      'thpt-pct-pt-schema-migrations',
    ]);
    client.release();
    await closeDatabasePool();
  }
}

run().catch((error) => {
  logger.error(
    { error: error instanceof Error ? error : { message: String(error) } },
    'Database migration failed',
  );
  process.exitCode = 1;
});
