CREATE TABLE IF NOT EXISTS imported_contents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_site VARCHAR(255) NOT NULL,
  source_url VARCHAR(1000) NOT NULL,
  title VARCHAR(500) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  excerpt TEXT NULL,
  content_html LONGTEXT NULL,
  content_text LONGTEXT NULL,
  category_name VARCHAR(255) NULL,
  detected_published_at DATETIME NULL,
  images_json JSON NULL,
  attachments_json JSON NULL,
  import_status ENUM('pending', 'imported', 'converted', 'skipped', 'error') NOT NULL DEFAULT 'pending',
  imported_post_id INT UNSIGNED NULL,
  error_message TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_imported_contents_source_url (source_url(768)),
  KEY idx_imported_contents_status (import_status),
  KEY idx_imported_contents_category (category_name),
  KEY idx_imported_contents_created_at (created_at),
  KEY idx_imported_contents_imported_post_id (imported_post_id)
);
